### ISSUE TITLE
Add some useful items

### ISSUE THREAD

**Issue by pacotudel** [romainsi/zabbix-VEEAM_B-R#15]
Hi! 
First thanks for this template, it's very useful on my job! We have some Veeam and i'm working with zabbix to see if backups go well :)

I'v added 2 items that are very useful for me on my implementation:

"LastRun" {
	$query = Get-VBRJob | Where-Object {$_.Id -like "*$ID*"}
	$query.ScheduleOptions.LatestRun.ToString("dd/MM/yyyy hh:mm:ss")
  }
  "TimeFromLast" {
	$query = Get-VBRJob | Where-Object {$_.Id -like "*$ID*"}
	$res = Get-Date
	$res -= [datetime]$query.ScheduleOptions.LatestRunLocal
	[int]$res.TotalHours
  }

LastRun gives date and time of last execution of a job
TimeFromLast gives time in hours from last backup, with this i can graph and see if more than 24 hours from last backup (ok or not ok backup)

Saludos from spain!

**Comment by romainsi** [comment]
Hi, 

Thanks, I'll add this feature when I have a little while ;)

**Comment by romainsi** [comment]
Done
