### ISSUE TITLE
Value should be a JSON object

### ISSUE THREAD

**Issue by alirezazabihi** [romainsi/zabbix-VEEAM_B-R#16]
Hi dear,
Thanks for your great job,
I have a problem and in discovery windows i get "Value should be a JSON object" for some discovery rules,
Actually I cannot find backupjob.xml file in C:\Program Files\Zabbix agent\scripts\ ?!
Could you please help me about this issue ?!
and if you can tell me clearly about regular expressions ! first one is ok, but about second one i cant understand.
thanks in advance

**Comment by romainsi** [comment]
Hi, please update with V3.
