### ISSUE TITLE
Error Teample errror.I want to help Please !

### ISSUE THREAD

**Issue by porzza99** [romainsi/zabbix-VEEAM_B-R#18]
1.Value "Import-Clixml : Could not find file 'C:\Program Files\Zabbix 
Agent\scripts\backupjob.xml'.
At C:\Program Files\Zabbix Agent\scripts\zabbix_vbr_job.ps1:273 char:11
+ $xml1 = Import-Clixml "$pathxml\backupjob.xml"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OpenError: (:) [Import-Clixml], FileNotFoundExce 
ption
+ FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.Im 
portClixmlCommand

0" of type "string" is not suitable for value type "Numeric (unsigned)"

2.Value "-- ERROR -- : Need an option !" of type "string" is not suitable for value type "Numeric (unsigned)

**Comment by ellucas123** [comment]
I am having the same error, I run it directly on the server through zabbix_get and the following error occurs:

I removed the -ErrorAction SilentlyContinue parameter from the command below to see the error.
`Add-PSSnapin -Name VeeamPSSnapIn -ErrorAction SilentlyContinue`


`Add-PSSnapin: No Snap-in Has Been Registered for Windows PowerShell Version 5.
No C: \ Zabbix \ scripts \ zabbix_vbr_job.ps1: 38 character: 1
+ Add-PSSnapin -Name VeeamPSSnapIn # -ErrorAction SilentlyContinue
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo: InvalidArgument: (VeeamPSSnapIn: String) [Add-PSS
   napin], PSArgumentException
    + FullyQualifiedErrorId: AddPSSnapInRead, Microsoft.PowerShell.Commands.Ad
   dPSSnapinCommand

Command Send
Connect-VBRServer: The term 'Connect-VBRServer' is not recognized as a
cmdlet, function, script file, or operable program. Check the spelling of the
name or, if a path has been included, see if the path is correct and
try again.
No C: \ Zabbix \ scripts \ zabbix_vbr_job.ps1: 166 character: 19
+ $ connectVeeam = Connect-VBRServer
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo: ObjectNotFound: (Connect-VBRServer: String) [], C
   ommandNotFoundException
    + FullyQualifiedErrorId: CommandNotFoundException
`

**Comment by romainsi** [comment]
Hi, old versions < 7.0 doesn't support Connect-VBRServer and Add-PSSnapin -Name VeeamPSSnapIn.
You can delete this lines in powershell scripts.
