### ISSUE TITLE
i use zabbix-VEEAM ,Error

### ISSUE THREAD

**Issue by porzza99** [romainsi/zabbix-VEEAM_B-R#20]
Value "Import-Clixml : Could not find a part of the path 'C:\Program Files\Zabbix 
Agent\scripts\TempXmlVeeam\backupjob.xml'.
At C:\Program Files\Zabbix Agent\scripts\zabbix_vbr_job.ps1:395 char:11
+ $xml1 = Import-Clixml "$pathxml\backupjob.xml" | Measure-Obje ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OpenError: (:) [Import-Clixml], DirectoryNotFoun 
dException
+ FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.Im 
portClixmlCommand

0" of type "string" is not suitable for value type "Numeric (unsigned)"

**Comment by zhukovd** [comment]
I have same problem.

**Comment by romainsi** [comment]
Hi, the error message say : DirectoryNotFoundException.
Can you verify if 'C:\Program Files\ZabbixAgent\scripts\TempXmlVeeam\backupjob.xml' is present ?
If not, you can use item Result Export Xml Veeam or the powershell command :  "C:\Program Files\Zabbix Agent\scripts\zabbix_vbr_job.ps1" exportxml

If you have just added the template, you must wait at least 1 hour for the results.

**Comment by porzza99** [comment]
![image](https://user-images.githubusercontent.com/38149024/50809989-ae4f3180-1339-11e9-95a0-ca3a3f8dcdda.png)
Path is ok

**Comment by porzza99** [comment]
![image](https://user-images.githubusercontent.com/38149024/50810445-46e6b100-133c-11e9-95d9-b84cdc1e4f21.png)
