### ISSUE TITLE
Quelques soucis pour mettre en place le template

### ISSUE THREAD

**Issue by mulbzh** [romainsi/zabbix-VEEAM_B-R#21]
Bonjour,

Au niveau de l'agent, pas de soucis.

C'est plutôt au niveau des expressions régulières a rajouter dans Zabbix. Vous indiquez :
In Zabbix : Administration, General, Regular Expression : Add a new regular expression :
Name : "Veeam" ; Expression type : "TRUE" ; Expression : "Veeam.*"
And modify regular expression "Windows service startup states for discovery" : Add : 
Name : "Veeam" ; Expression type : "FALSE" ; Expression : "Veeam.*"

Pour le 1er, pas de souci, j'ai créé l'expression régulière.

Par contre, pour le 2eme (Windows service startup states for Discovery), il est indiqué d'ajouter le nom "Veeam". Hors, quand je modifie l'expression régulière, je ne peux pas ajouter de nom, Je ne peux que choisir le type d'expression et l'expression.

Je ne comprends pas.

J'ai rajouté le Template sur l'hote mais quand je veux remettre le Template OS Windows, j'ai :
"La règle de découverte "service.discovery" existe déjà sur "SOCSAVE15", héritée d'un autre modèle. [hosts.php:681 → CApiWrapper->__call() → CFrontendApiWrapper->callMethod() → CApiWrapper->callMethod() → CFrontendApiWrapper->callClientMethod() → CLocalApiClient->callMethod() → CHost->update() → CHost->massUpdate() → CHost->massAdd() → CHostGeneral->massAdd() → CHostGeneral->link() → CDiscoveryRule->syncTemplates() → CDiscoveryRule->inherit() → CItemGeneral->prepareInheritedItems() → CApiService::exception() in include/classes/api/services/CItemGeneral.php:998]"

merci pour l'aide

**Comment by mulbzh** [comment]
a priori pour mon 2eme souci, j'ai trouvé, j'ai tout simplement lié le Template Veeam au Template Windows

Par contre, il me reste toujours le 1er souci

**Comment by almorr** [comment]
Salut
pour ton premier souci: il faut ajouter une expression sous Regular expressions à Windows service startup states for discovery. Regrades le screenshot:
https://ibb.co/kJGZLq4

**Comment by mulbzh** [comment]
Ok, parfait, c'est effectivement ce que j'ai fait !

Par contre, j'ai des remontées sur les status de Veeam qui sont bien remontées mais pas sur le reste.
Sur le serveur Veeam, j'ai lancé le script en PowerShell avec l'option exportxml, cela fonctionne !

Je viens d'augmenter le timeout à 30 sur l'agent pour voir

**Comment by mulbzh** [comment]
il manque juste cela qui ne fonctionne pas "problème de récupération données Backup Veeam"

Les XML sont bien générés
j'ai augmenté le timeout à 30

beaucoup parlent de la variable $pathsender, mais je ne vois pas où elle est ? pas trouvé dans le script, ni dans le Template

**Comment by romainsi** [comment]
Bonjour à priori vous vous en êtes sortis ^^

Sinon c'est indiqué dans la doc : 
Purge and clean Template OS Windows if is linked to the host (you can relink it after).

La variable $pathsender n'existe plus dans cette version, elle était utilisé avec l'ancienne version qui faisait appel à des items Trappers.

**Comment by mulbzh** [comment]
non, j'ai toujours dans Zabbix : "probleme de recuperation des données backup Veeam"
Ce qui est étonnant, c'est que dans Zabbix "dernières données, a priori j'ai bien les remontées :

Voir la capture écran https://ibb.co/HrJD9zJ

**Comment by mulbzh** [comment]
Voilà : https://ibb.co/k3XWnyb

**Comment by romainsi** [comment]
Pour moi tout à l'air correct ... Peut-être essayer de délié le template (avec purge) et le remettre en place
