### ISSUE TITLE
Plusieurs messages d'erreur

### ISSUE THREAD

**Issue by IlianCMB** [romainsi/zabbix-VEEAM_B-R#22]
Après avoir suivi les instructions pour déployer le script, l'agent, etc. J'ai plusieurs messager d'erreur qui ont l'air de venir du script.
Le premier à n'importe quel lancement du script : 
```
PS C:\Program Files\Zabbix Agent\scripts> .\zabbix_vbr_job.ps1 RunningJob
Opérateur « = » manquant après un argument nommé.
Au niveau de C:\Program Files\Zabbix Agent\scripts\zabbix_vbr_job.ps1 : 117 Caractère : 38
+     Param ([Parameter(ValueFromPipeline) <<<< ]
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : MissingEqualsInNamedArgument
```

J'ai fini par modifier la ligne 117 	Param ([Parameter(ValueFromPipeline)] par 	Param ([Parameter(ValueFromPipeline = $true)]

Après cela j'ai l'erreur suivante : 
```
PS C:\Program Files\Zabbix Agent\scripts> .\zabbix_vbr_job.ps1 RunningJob
Import-Clixml : Impossible de trouver le fichier 'C:\Program Files\Zabbix Agent\scripts\TempXmlVeeam\backupjob.xml'.
Au niveau de C:\Program Files\Zabbix Agent\scripts\zabbix_vbr_job.ps1 : 441 Caractère : 24
+         $xml1 = Import-Clixml <<<<  "$pathxml\backupjob.xml"
    + CategoryInfo          : OpenError: (:) [Import-Clixml], FileNotFoundException
    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.ImportClixmlCommand
 
0
```
Je ne suis pas expert en PS mais j'ai l'impression que les fichiers XML ne sont jamais générés....
En tout cas merci d'avance !
Ilian

**Comment by romainsi** [comment]
Bonjour,

J'ai modifié le scripts qui fonctionner sans problème sur mon infrastructure jusqu'à présent et fonctionne également avec ce paramètre.
Quelle version d'OS, Powershell est utilisé ?

Pour généré les fichiers xml tu peux utiliser la commande suivante :
`PS C:\Program Files\Zabbix Agent\scripts> .\zabbix_vbr_job.ps1 ExportXml`

**Comment by IlianCMB** [comment]
Bonjour,
Merci pour ta réponse.
J'ai recopié ta nouvelle version du script et ai lancé la commande que tu m'a donné.
Résultat : 
```
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. Tous droits réservés.

PS C:\Windows\system32> PS C:\Program Files\Zabbix Agent\scripts> .\zabbix_vbr_job.ps1 ExportXml
Get-Process : Impossible de trouver un paramètre positionnel acceptant l'argument « Files\Zabbix ».
Au niveau de ligne : 1 Caractère : 3
+ PS <<<<  C:\Program Files\Zabbix Agent\scripts> .\zabbix_vbr_job.ps1 ExportXml
    + CategoryInfo          : InvalidArgument: (:) [Get-Process], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.GetProcessCommand
```
Je suis sur un Windows 7 pro..

**Comment by romainsi** [comment]
Bonjour,

Je me suis mal exprimer ^^
La commande à exécuter et la suivante : 
`**cd  "C:\Program Files\Zabbix Agent\scripts"**`
puis
`.\zabbix_vbr_job.ps1 ExportXml`
La commande peut être longue a s'exécuter, cela dit il faut aussi que le client Zabbix soit installé a cet emplacement ...
Après cette commande les fichiers xml sont générés à l'emplacement : C:\Program Files\Zabbix Agent\scripts\TempXmlVeeam\*.xml
