### ISSUE TITLE
Backupsession.xml no longer generated

### ISSUE THREAD

**Issue by STAV550** [romainsi/zabbix-VEEAM_B-R#23]
Bonjour,

J'ai procédé à la mise à jour en V4 de mon agent Zabbix sur mon serveur Veeam il y a quelques jours. Depuis cette mise à jour, le fichier backupsession.xml n'est plus généré automatiquement. Je l'ai généré manuellement et aucune erreur ne s'est produite. J'ai bien suivi les directives pour l'installation pour le script. J'ai 4 fichiers XML qui se créaient automatiquement mais ils n'y a que l'en-tête du XML.

![vmconnect6 3_y40jsq3wqe](https://user-images.githubusercontent.com/42958487/51536181-08c4b380-1e4b-11e9-94e6-c458d7643288.png)
![vmconnect6 3_gjb8y8hbvo](https://user-images.githubusercontent.com/42958487/51536182-08c4b380-1e4b-11e9-882e-e9b2adbb0c01.png)

Avant mon agent était en V3.4.6 et tout fonctionnait correctement. Tout naturellement, j'ai rétrogradé de la V4 à la V3.4.6 pour voir si tout redevenait normal et il s'avère que non.

Dans le log de l'agent Zabbix, je vois bien la ligne de commande pour l'exécution du script qui se lance bien toutes les 20 min.

Merci pour votre aide.

**Comment by romainsi** [comment]
Bonjour,

Il me semble que cela est du a la connexion au module veeam ...
Il faudrait lancer la commande powershell suivante pour voir le retour :
`.\zabbix_vbr_job.ps1 exportxml`

**Comment by STAV550** [comment]
Bonjour,

Merci de votre réponse.

En lançant la commande manuellement, tous les fichiers XML se génèrent bien avec les bonnes informations dedans.
Output de PS : "Command Send" et aucune erreur générée.

Mais, les fichiers suivant ne se regénèrent pas automatiquement :

- backuptape.xml
- backupsession.xml
- backupjob.xml
- backupendpoint.xml
- backupbackup.xml

Il n'y a que les 4 fichiers de mon premier message qui se regénèrent tout en perdant les infos acquises lors de l'exécution manuelle.

![gdw71awvbr](https://user-images.githubusercontent.com/42958487/51688071-17020380-1ff4-11e9-96d2-3fbf4bd9d649.png)

**Comment by romainsi** [comment]
Bonjour,

Je suis quasiment certain que c'est dû à un problème de droit d'exécution lorsque le serveur envoi la demande.
Pour en savoir plus il faudrait activer le debug de l'agent (zabbix_agentd.conf DebugLevel=3 ou 4 & restart service) puis voir ce qu'il renvoi.
Les paramètres `EnableRemoteCommands=1` & `UnsafeUserParameters=1` sont bien renseignés dans le zabbix_agentd.conf ?
Sa peut aussi être lié au [set-executionpolicy](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-6) 
Pour tester il peut être modifié par : `set-executionpolicy unrestricted`

**Comment by romainsi** [comment]
Egalement tester ceci :

Sur le serveur Zabbix en ssh :
`zabbix_get -s "le_nom_dns_ou_ip_du_client_veeam" -k 'system.run[powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent\scripts\zabbix_vbr_job.ps1" exportxml]'`

Ou de modifier sur le template zabbix (WebUI) l'item suivant : 
`Resultat Export Xml Veeam` et de retirer le `,nowait` à la fin, il devrait renvoyer l'erreur powershell.
