### ISSUE TITLE
No replication job

### ISSUE THREAD

**Issue by OndrejBalaz** [romainsi/zabbix-VEEAM_B-R#29]
None of my replication jobs was discovered and monitored. Other backup jobs and backup copy jobs are OK.

**Comment by itRACS** [comment]
I also have found this issue. 

Was attempting to start adding tot he templates and script but i feel this would be worth more to everyone if your excellent template include Get-VBRReplica

**Comment by romainsi** [comment]
Hi, 

Please update to V3.3.

Romain.
