### ISSUE TITLE
Discovery rule "service.discovery" already exists

### ISSUE THREAD

**Issue by vfrans** [romainsi/zabbix-VEEAM_B-R#30]
Hi,

It looks like it is impossible to link both Veeam Template and Windows OS at the same time. Tried on existing host, new host. When trying it on new host, always unlinked windows with purge.

I really don't know what to try anymore..
![Screenshot 2019-05-07 at 14 49 07](https://user-images.githubusercontent.com/12429639/57300972-31aa4500-70d8-11e9-843c-ff77646dcd24.png)

**Comment by romainsi** [comment]
Hi,

In the host you must have an item service discovery (not necessarily the template windows...), it is absolutely necessary to purge/delete it before you can link this template.

**Comment by TarrX** [comment]
I do have the same issue with the current version. I had an existing host, connected by a proxy. I removed that host. Created it new with just your Template. Then tried to add Windows OS, and I do get the same error message, not allowing me to add the Windows OS Template.

**Comment by vfrans** [comment]
FYI, I was not able to actually configure it right (but I'm fairly new to zabbix so it might something I'm doing wrong)

**Comment by TarrX** [comment]
The plugin itself is running quite well so far, it is just that I would like to have the interface statistics back.
