### ISSUE TITLE
fichiers XML vides

### ISSUE THREAD

**Issue by Deubow** [romainsi/zabbix-VEEAM_B-R#32]
Bonjour,

j'ai suivi à la lettre ton tuto, mais je rencontre plusieurs problèmes.

Tout d'abord, le script ne semble pas s’exécuter tout seul. J'ai bien mis la ligne de commande dans le fichier de conf de l'agent.

D'autre part, lorsque je l’exécute à la main, pour la génération des fichiers xml, ceux ci sont vides :-/

As-tu déjà rencontré ce type de problème ? 

Merci,

**Comment by Deubow** [comment]
En exécutant le script dans un Powershell en tant qu'admin ça fonctionne mieux. Les fichiers XML contiennent bien les data.

En revanche, l'agent Zabbix ne semble toujours pas vouloir l’exécuter tout seul.

**Comment by Deubow** [comment]
J'avance, j'avance... le chemin dans le template pour l’exécution du script n'était pas bon. Donc maintenant, l'agent Zabbix exécute bien le script, mais il n'y a pas de data dans les XML.

Comme lorsque j’exécutais le script sans cliquer sur "exécuter en tant qu'administrateur". J'ai loupé quelque chose pour que l'agent zabbix exécute le script en tant qu'administrateur ?

**Comment by romainsi** [comment]
Bonjour,

Regarder si vous n'avez pas un problème d'UAC, ou d'execution-policy de powershell.
Si vous avez changer le chemin par défaut dans le script, il faut aussi modifier l'item suivant dans zabbix sur le template :
system.run[powershell -NoProfile -ExecutionPolicy Bypass -File "C:\Program Files\Zabbix Agent\scripts\zabbix_vbr_job.ps1" exportxml,nowait]

et changer par le nouvel emplacement.

![image](https://user-images.githubusercontent.com/30522413/59104663-648f6500-8932-11e9-80fa-af5882c752f2.png)
