### ISSUE TITLE
Veeam Backup Data Recovery Problem

### ISSUE THREAD

**Issue by itRACS** [romainsi/zabbix-VEEAM_B-R#33]
Hi,

I have updated to your latest version of the script to include Replica jobs. 

I am sure it's something i have done wrong but i am receiving this trigger:

Veeam Backup Data Recovery Problem
:vbr[ResultReplica,f483388c-a911-4690-b5f6-f85eb431b53e].nodata(7200)}=1

Any suggestions on how to resolve?

**Comment by OndrejBalaz** [comment]
I have a lot of false positive triggers in replication jobs

Backup {#JOBREPLICANAME} Warning
Backup {#JOBREPLICANAME} Failed

**Comment by romainsi** [comment]
Hi itRACS,

Please check if the replication jobs do not end in timeout.
If the problem is this one, increase the timeout in zabbix_agentd.conf on the client.

Example of timeout on an item that produces an erroneous trigger :

![image](https://user-images.githubusercontent.com/30522413/59973426-19b35580-95a0-11e9-85fb-312ec1acff26.png)

**Comment by itRACS** [comment]
Thank you for your reply.

I do not see any issues relating to "Timeout while executing a shell script" but i am getting this. see pic.
![Screenshot 2019-06-24 at 14 11 54](https://user-images.githubusercontent.com/50620617/60021884-b6eab880-968a-11e9-9f05-be273ec0e14c.png)

**Comment by romainsi** [comment]
Ok, I see that the "type" values are empty but I updated the script for the backup "type" that does not work with replication (not released) but triggers do not use these elements.

Do you have any results data that go back?

**Comment by itRACS** [comment]
We have 8 replica jobs. 5 run on every 90 minutes throughout the day. 3 are daily.

None of the replicas are showing as receiving data. What trouble shooting steps do you recommend to find the cause?
![Screenshot 2019-06-25 at 16 04 30](https://user-images.githubusercontent.com/50620617/60109827-f389e300-9762-11e9-852a-2d2018507bac.png)

**Comment by romainsi** [comment]
Please verify if *.xml are presents and not empty.

**Comment by itRACS** [comment]
All present yes. they have always been there. 

I have double checked everything by re-downloading your ps1 file, deleting the xml's and allowing to re-create. i have removed the template altogether from zabbix and unlinked and cleared them from the host. then re-imported the template.

Again, i thank you for your patience.

**Comment by romainsi** [comment]
Okay, perfect ! ;)

**Comment by itRACS** [comment]
Sorry i think you miss understand me. All the xml files seem to be present.

The script has always been creating the xml files but i still have the issue that no data from my replicas are showing. 

I was just letting you know, i have repeated your install instruction in case i missed something hoping it would resolve the issue, but it hasn't.

Sorry for the confusion. 

Am i potentially missing an xml required?

**Comment by itRACS** [comment]
Are you able to open the issue again?

**Comment by romainsi** [comment]
On zabbix server please try this :

`zabbix_get -s "IPSERVERVEEAM" -k 'vbr[ResultReplica,TASKID]'`

**Comment by itRACS** [comment]
Hi,

just to confirm this is to be run on the actual zabbix server? running on ubuntu.

It cannot find the command. I have only seen zabbix_get on a host with the zabbix agent installed? do i first need to install the agent on the server?

**Comment by romainsi** [comment]
Hi,

Yes on the server ^^ Look [here](http://www.zabbix.com/documentation/4.0/manual/concepts/get)
If you've the zabbix appliance on ubuntu it's installed by default.

**Comment by itRACS** [comment]
Cheers, ran your command eg. zabbix_get -s "192.168.0.15" -k 'vbr[ResultReplica,TASKID]'

the result is '4'

**Comment by romainsi** [comment]
Hum ... so query return result but not zabbix UI ...

Look /var/log/zabbix/zabbix_server.log to try to find the error.
Verify on host that zabbix_agentd.conf contains the ServerActive with your zabbix server.

**Comment by MekaBee** [comment]
I am having an issue with VEEAM ReplicaBackup Jobs, as well.
I am getting a timeout error, even though I set zabbix_agentd to Timeout=30 (I believe that's the max)? 

I have only used the latest version of this template. My XML files are about 100 MB. 

Any advice? 

BTW - thanks for making and sharing this. Awesome template.

**Comment by romainsi** [comment]
Hi MekaBee,

Please modify timeout on server too.

**Comment by cloudlgti** [comment]
Hi romainsi,
I have your script  running, my .xmls with 1KB Space.

![Captura de Tela 2020-01-17 às 16 23 03](https://user-images.githubusercontent.com/50424091/72639951-909daa80-3945-11ea-8627-65588d4cc121.png)
