### ISSUE TITLE
I have a lot of false positive triggers in replication jobs

### ISSUE THREAD

**Issue by romainsi** [romainsi/zabbix-VEEAM_B-R#34]
I have a lot of false positive triggers in replication jobs

Backup {#JOBREPLICANAME} Warning
Backup {#JOBREPLICANAME} Failed

_Originally posted by @OndrejBalaz in https://github.com/romainsi/zabbix-VEEAM_B-R/issues/33#issuecomment-502551807_

**Comment by romainsi** [comment]
Hi, please send more informations :)

**Comment by OndrejBalaz** [comment]
Veeam backup 9.5 update 4 version 9.5.4.2753 installed on Windows Server 2012 R2. I have 2 replication jobs, that run every hour. Item of Replication job is checked at interval 600. In Veeam console, I see that replication job finished successful, in zabbix console is Failed (0)

**Comment by romainsi** [comment]
Hi,

Mistake in script please update with last release.

Thx.
