### ISSUE TITLE
Sauvegarde de type EpAgentManagement

### ISSUE THREAD

**Issue by ThomasSo01** [romainsi/zabbix-VEEAM_B-R#36]
Bonjour,

Il semble que les sauvegardes de type EpAgentManagement ne soient pas découvertes ni gérer aujourd'hui.
Il s'agit des sauvegardes agent gérées côté serveur et non côté agent.

Pouvez vous m'indiquer comment procéder pour les avoir dans zabbix ?

Merci d'avance,

**Comment by romainsi** [comment]
Bonjour,

Est-ce cela : https://helpcenter.veeam.com/docs/backup/powershell/get-vbrepjob.html?ver=95u4 ?

**Comment by ThomasSo01** [comment]
Bonjour,
Non, il ne ressort pas avec cette commande.
Je le retrouve en faisant un Get-VBRJob.

**Comment by romainsi** [comment]
Bonjour,

Je n'arrive pas à reproduire ce type de backup dans VeeamB&R ... 
Pouvez vous me donner la procédure de création de ce type de job ?

**Comment by ThomasSo01** [comment]
Bonjour,
Je vais sur Jobs -> Backups. 
Clic-droit -> Backup -> Windows computer
La fenetre "New Agent Backup Job" s'ouvre.
Type : Server - Mode : Managed by backup server

**Comment by romainsi** [comment]
Essayer avec sa : 

[Script](https://github.com/romainsi/zabbix-VEEAM_B-R/blob/dev/zabbix_vbr_job.ps1)
[TemplateV4.x](https://github.com/romainsi/zabbix-VEEAM_B-R/blob/dev/Template%20FR/Zabbix-V4.X-only-TemplateVEEAM-BACKUP-FR.xml)

**Comment by ThomasSo01** [comment]
Merci.
Par contre, j'ai un problème un peu bête je pense mais je vois pas comment contourner :/
Lors de l'import du template, j'ai une erreur : 
Discovery rule "service.discovery" already exists on "ServeurBackup", inherited from another template.

**Comment by ThomasSo01** [comment]
C'est bon, j'ai enlevé le template Windows (Unlink and clear) et j'ai pu mettre à jour.
