### ISSUE TITLE
Windows services autostart monitoring works wrong after activating the plugin

### ISSUE THREAD

**Issue by jochenwezel** [romainsi/zabbix-VEEAM_B-R#39]
Since installation of veeam plugin in zabbix, we get lot of windows service warnings for windows services, but their names are on the exclude list:
![image](https://user-images.githubusercontent.com/3033827/65161744-6213cf80-da38-11e9-8c0f-b9a9bedfa17a.png)

## Environment and used plugin install guide
Used Install Guide: https://share.zabbix.com/cat-app/backup/veeam-backup-recovery-jobs-trapper
Veeam Version: latest Update 4
Zabbix Version: 4.2.6

## Assumption of problem source
The install guide explain to add a regular expression "Veeam.*" to "Windows service startup states for discovery".
I could imagine, the guide is wrong and it should be the entry "Windows service names for discovery" (either as separate, 2nd expression OR somehow integrated into the 1st expression)

![image](https://user-images.githubusercontent.com/3033827/65161394-caae7c80-da37-11e9-9999-9caf24430415.png)

**Comment by Ceillian** [comment]
I'm so glad I reviewed the open cases. I deployed this an hour or so ago and mindlessly followed the guide. Luckily, my instance didn't get filled with ignored services. I believe you assessment is correct. I cannot see a reason a service state would be set to "Veeam.*"

**Comment by romainsi** [comment]
Hi,

Yes it's an error, I had wanted to use this to have the Windows & Veeam services separated but the key services.discovery is unique so it is impossible to have a separate "group" like that.
I corrected the Readme and added a comment about it
