### ISSUE TITLE
Not getting result export XML Veeam

### ISSUE THREAD

**Issue by borovoykirill** [romainsi/zabbix-VEEAM_B-R#41]
Good day!

There is a problem, I did everything as per the instructions, but I can not get the result export XML Veeam.

Please, tell me where there may be a problem?

Thanks!

![items](https://user-images.githubusercontent.com/40700251/67157280-c3c6a280-f332-11e9-8eb9-89724602f1c8.png)
![latest data](https://user-images.githubusercontent.com/40700251/67157015-a263b780-f32e-11e9-9efe-c4cc5b8cde6a.png)
![Result](https://user-images.githubusercontent.com/40700251/67157016-a394e480-f32e-11e9-8761-062652698fd8.png)

**Comment by borovoykirill** [comment]
**N.B**
As can I see XML files are created but apparently are not accepted by zabix-server.
![XML](https://user-images.githubusercontent.com/40700251/67157319-49e2e900-f333-11e9-968f-6a0701ef09ec.png)

**Comment by borovoykirill** [comment]
Is there anyone?)

**Comment by borovoykirill** [comment]
Issue resolved.

**Comment by lcslex** [comment]
Hi there, i have the same problem, can you please tell me how did you solve this ? XML are generated however they are empty.

**Comment by borovoykirill** [comment]
> Hi there, i have the same problem, can you please tell me how did you solve this ? XML are generated however they are empty.

Hi, I already forgot about this problem, so much time has passed) Yes, I decided, as far as I remember, my problem was that the hostname in agent config did not match with hostname in Zabbix server. And when the agent tried to send information to Zabbix server, Zabbix server rejected info because the hostname did not match.
