### ISSUE TITLE
vbrJobResult gives me Success (2) when the real backup job Result is Failed 

### ISSUE THREAD

**Issue by FraFau** [romainsi/zabbix-VEEAM_B-R#46]
The original job fail cause is due to VM unavailable and which was skipped.
Is there a way to get the true failed trigger ?

**Comment by romainsi** [comment]
Please look the last result in **history** menu of veeam B&R

**Comment by FraFau** [comment]
Here you can view the Zabbix last result of the job :

Resultat Backup TEC-SERVEUR.BE10J | 03/02/2020 09:58:58 | Success (2)|-- | -- | --

and the VBR one :


Backup job: TEC-SERVEUR.BE10J (Retry 2)Created by ***** at 25/05/2016 22:51. | Error-- | --
Details :
Virtual Machine TEC.SERVEUR.BE is unavailable and will be skipped from processing.
Nothing to process. All machines were excluded from task list

**Comment by romainsi** [comment]
Hum it's strange ...
With powershell can you try this : 

`$xml = Import-Clixml 'C:\Program Files\Zabbix Agent\scripts\TempXmlVeeam\backuptaskswithretry.xml'`
`$xml | ?{$_.JobName -like 'TEC-SERVEUR.BE10J'} | Sort-Object JobStart -Descending | select -First 5`

And send me the result :)

**Comment by FraFau** [comment]
Hi Romain, 

Here are the result lines you wished

JobName     : TEC-SERVEUR.BE10J
JobId       : e73178c7-5fb1-4cc5-8eb2-d1d91e38c3ae
SessionName : TEC-SERVEUR.BE10J (Incremental)
JobResult   : Success
JobStart    : 14/01/2020 20:16:19
JobEnd      : 14/01/2020 20:19:25
Date        : 2020-01-14
Name        : TEC.SERVEUR.BE
Status      : Success

JobName     : TEC-SERVEUR.BE10J
JobId       : e73178c7-5fb1-4cc5-8eb2-d1d91e38c3ae
SessionName : TEC-SERVEUR.BE10J (Incremental)
JobResult   : Success
JobStart    : 13/01/2020 20:21:39
JobEnd      : 13/01/2020 20:25:47
Date        : 2020-01-13
Name        : TEC.SERVEUR.BE
Status      : Success

JobName     : TEC-SERVEUR.BE10J
JobId       : e73178c7-5fb1-4cc5-8eb2-d1d91e38c3ae
SessionName : TEC-SERVEUR.BE10J (Synthetic Full)
JobResult   : Success
JobStart    : 12/01/2020 21:46:40
JobEnd      : 12/01/2020 21:54:04
Date        : 2020-01-12
Name        : TEC.SERVEUR.BE
Status      : Success

JobName     : TEC-SERVEUR.BE10J
JobId       : e73178c7-5fb1-4cc5-8eb2-d1d91e38c3ae
SessionName : TEC-SERVEUR.BE10J (Incremental)
JobResult   : Success
JobStart    : 10/01/2020 20:12:39
JobEnd      : 10/01/2020 20:15:54
Date        : 2020-01-10
Name        : TEC.SERVEUR.BE
Status      : Success

JobName     : TEC-SERVEUR.BE10J
JobId       : e73178c7-5fb1-4cc5-8eb2-d1d91e38c3ae
SessionName : TEC-SERVEUR.BE10J (Incremental)
JobResult   : Success
JobStart    : 09/01/2020 20:15:50
JobEnd      : 09/01/2020 20:19:05
Date        : 2020-01-09
Name        : TEC.SERVEUR.BE
Status      : Success

It sounds weird for me !

**Comment by romainsi** [comment]
I feel like the XML files aren't up to date, the last backup date is 14.01.2020 with success so zabbix return Success for last backup.

Update him manually with powershell : 
`cd 'C:\Program Files\Zabbix Agent\scripts'`
`.\zabbix_vbr_job.ps1 exportxml`

Verify update with (look JobStart) : 
`$xml = Import-Clixml 'C:\Program Files\Zabbix Agent\scripts\TempXmlVeeam\backuptaskswithretry.xml'`
`$xml | ?{$_.JobName -like 'TEC-SERVEUR.BE10J'} | Sort-Object JobStart -Descending | select -First 5`

**Comment by FraFau** [comment]
It gives me exactly the same result, because this was the date of the last succeed backup

**Comment by romainsi** [comment]
You use Veeam Backup & Replication V9 or Veeam Community Edition ?

**Comment by FraFau** [comment]
VBR 9.5u4

**Comment by romainsi** [comment]
I'm sorry but I can't reproduce the problem ...

Look the screenshots :

![1](https://user-images.githubusercontent.com/30522413/73753817-90821500-4763-11ea-9802-3d9ee5923238.png)
![2](https://user-images.githubusercontent.com/30522413/73753828-9546c900-4763-11ea-9412-3cfa2159ac7f.png)
